### PR TITLE
tsconfig.json

### PR DESCRIPTION
**Pull request by ivogabe**
```javascript
var tsProject = ts.createProject('tsconfig.json');

gulp.task('default', function() {
    return tsProject.src()
        .pipe(ts(tsProject))
        .pipe(gulp.dest('release'));
});
```

### CODE REVIEW

**Comment by J-F-Liu** [comment]
Looks good!

**Comment by ifyio** [comment]
Hi. I'm trying to move to `tsconfig.json`. In my gulp file, I'm doing the following:

```
var tsProject = ts.createProject('tsconfig.json', {
    typescript: typescript
});

gulp.task('build-ts', [], function() {
    return gulp.src(paths.typescript)
        .pipe(plumber())
        .pipe(sourcemaps.init())
        .pipe(ts(tsProject))
        .pipe(sourcemaps.write())
        .pipe(gulp.dest(paths.output));
});
```

And `tsconfig.json` looks like 

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "emitDecoratorMetadata": true,
        "noExternalResolve": true,
        "declarationFiles": false
    }
}
```

I'm getting the following error however... `1148 Cannot compile external modules unless the '--module' flag is provided.`. Am I doing something wrong?

**Comment by ivogabe** [comment]
That's strange, for me it works. Just to be sure, do you use the master of gulp-typescript from GitHub, and not the release on npm?

**Comment by ifyio** [comment]
I'm using version 2.6.0

**Comment by ifyio** [comment]
Ah. It's from npm

**Comment by ifyio** [comment]
I will try it now with the the one directly from github

**Comment by ifyio** [comment]
Ok it works now when I use the master of gult-typescript from GitHub. Thanks. Will npm be updated?

**Pull request merged**
