### PR TITLE
Update from TSD to typings

### LINKED ISSUE #436: node_modules/gulp-typescript/typings/tsd.d.ts not found.
I'm using Typescript 2, to install types I just run `@types/LIBRARY_NAME`, I no longer have a typings folder, which is specially not needed since this library exports its types data.

However, this line in `release/main.d.ts(1,1)` is giving me an issue:
`/// <reference path="../typings/tsd.d.ts" />`

The module no longer has a typings folder when I install it with npm so this is referencing an inexistent folder. I get rid of that line and the error goes away. This is the error I'm seeing:

`release/main.d.ts(1,1): error TS6053: File '/Users/gabriel/work/project_one/node_modules/gulp-typescript/typings/tsd.d.ts' not found.`

### PR DESCRIPTION
**Pull request by demurgos**
Hi,
This PR updates the definition files management from TSD to [typings](https://github.com/typings/typings) and fixes #436.

The build instructions were updated to include `typings install` after `npm install`.

I could [successfully build `gulp-typescript`](https://travis-ci.org/demurgos/gulp-typescript/builds/168709632) and was I able to remove the warning I got as a consumer (`tsd.d.ts not found`), but I'd still be careful with this PR to ensure that it does not introduce any breaking changes.

### CODE REVIEW

**Comment by demurgos** [comment]
Hi,
I know that this is a change in the build process so it requires some time to review it. Do you need more details ? I would gladly help you clarify and test any potential issues.

I have some dependent packages that throw some errors because of #436 and I hoped to solve it quickly.

**Comment by ivogabe** [comment]
Sorry for the late reply, I didn't have time to look at this earlier. I also looked at your `types` branch, and got that working after two changes. You accidentally included both types and typings, so all libraries were declared twice. The tests would also pick up the `@types` files, which broke several tests. I explicitly excluded the `@types` files and now all tests pass again. Can you take a look at #448 and see whether that works for you?

**Comment by demurgos** [comment]
Ok, I'll check that.

**Comment by demurgos** [comment]
I am closing this PR in favor of #448.

**Pull request closed without merging**
