### PR TITLE
Fixed the for in loop.

### PR DESCRIPTION
**Pull request by StefanKoenen**
The for-in loop was iterating over an array of strings, which results in the numeric indices of the array instead of the filenames.
Changed to the default for loop.
[http://stackoverflow.com/a/7480175](http://stackoverflow.com/a/7480175)

### CODE REVIEW

**Comment by ivogabe** [comment]
Good catch! I think it would be even better to use a for-of loop there, can you change that?

**Comment by StefanKoenen** [comment]
Thanks, but why would you prefer the for-of loop? It's getting compiled to the same;
(the first loop = for-of, second = for)
[https://xevro.nl/sharex/atom_2016_04_17_13_40_20_45008a61-3b98-4d64-802e-a48ce9fb597f.png](https://xevro.nl/sharex/atom_2016_04_17_13_40_20_45008a61-3b98-4d64-802e-a48ce9fb597f.png)

**Comment by ivogabe** [comment]
The for-of loop is more readable, has less noise in my opinion.

**Comment by StefanKoenen** [comment]
Updated...

**Comment by ivogabe** [comment]
You can still use a `const` there, can you change that? After that, I'll merge it

**Comment by StefanKoenen** [comment]
Done.
Please note this is an important change. In projects I work on the TS get's compiled while i only change the HTML because these checks were incorrect.

**Comment by ivogabe** [comment]
Thanks!

**Pull request merged**
