### PR TITLE
update version of TypeScript peer dependency

### PR DESCRIPTION
**Pull request by vladima**
- reflect [version update](https://github.com/Microsoft/TypeScript/blob/master/package.json#L5) in TypeScript nightly builds
- update `RawSourceMap` to [match changes](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/79f48dd449b0542cece6964b0cf761ee5316c435#diff-acd1cc7ef767fdde0d9d828f3deb3fca) on DefinitelyTyped

### CODE REVIEW

**Comment by ivogabe** [comment]
Thanks!

**Comment by vladima** [comment]
@ivogabe thanks for merging this in! Can you please tell when do you plan to release new version of `gulp-typescript` (so we can get this change in TypeScript nightlies)?

**Comment by ivogabe** [comment]
I'll quickly go through the other issues and release a new version today.

**Comment by ivogabe** [comment]
Released as 3.1.3

**Pull request merged**
