### PR TITLE
Inserts a `contributors` field to `package.json`

### PR DESCRIPTION
**Pull request by whitneyit**
Adds the names and email addresses for developers that have contributed
to the project.

### CODE REVIEW

**Comment by whitneyit** [comment]
/cc @jespermjonsson @shiwano @hakubo @poelstra @IlanFrumer

Does anyone have a problem with this?

**Comment by shiwano** [comment]
:+1:

**Comment by jespermjonsson** [comment]
👍

**Comment by poelstra** [comment]
Fine by me!

**Comment by hakubo** [comment]
:+1: I am proud to be on that list :)

**Comment by ivogabe** [comment]
Thanks, merged

**Pull request merged**
