### PR TITLE
update peer dependencies to support TS 2.3

### LINKED ISSUE #484: Update peer dependency to TypeScript 2.3
Recently version of TypeScript was [updated](https://github.com/Microsoft/TypeScript/blame/master/package.json#L5) to 2.3 however peer dependency in package.json is still limited to 2.2

### PR DESCRIPTION
**Pull request by vladima**
fixes #484

### CODE REVIEW

**Comment by vladima** [comment]
this is necessary to fix a build break in TS repo

**Comment by ivogabe** [comment]
I'll quickly go through some open issues and release the new version.

**Comment by vladima** [comment]
Thank you!

**Comment by ivogabe** [comment]
Released as 3.1.5!

**Pull request merged**
