### PR TITLE
Implementing Declaration maps

### PR DESCRIPTION
**Pull request by michaelaird**
This implements outputting declaration maps . Issue #574

### CODE REVIEW

**Comment by ivogabe** [comment]
Thanks Michael! I think it would be better if we could integrate it with gulp-sourcemaps. If I understand correctly, this new file follows the javascript source map format. (Correct me if I'm wrong.) We can emit those source maps the same way as we emit javascript sourcemaps, and let `gulp-sourcemaps.write` emit the sourcemaps. That would also mean that this would integrate with a preprocessor.

You would need to modify `outputDts` in `Output`. You can take a look at `outputJs`, which handles the JavaScript sourcemaps. Similarly to `declaration`, we could set `declarationMap` always to true. The user can then decide to emit them by adding `sourcemaps.write` to the declarations stream.

Can you make that change? Let me know if something is unclear or if I can help you with something.

**Comment by michaelaird** [comment]
I think I've captured what you were looking for. Let me know if you think there are other changes needed. Or feel free to make adjustments

**Comment by ivogabe** [comment]
Thanks for the quick changes, I’ll take a look at it friday or this weekend. The test failure is strange, as it shows some C functions in the error. It might be caused by some dependency that doesn’t support the latest node release. Have you tried googling the error message? It does succeed on LTS. I don’t think it has anything to do with your code btw.

**Comment by michaelaird** [comment]
Did you have a chance to review this yet? TS 2.9 was released last Friday and we'd like to take advantage of this functionality in our project.

**Comment by ivogabe** [comment]
Sorry, didn't have time for it. Will try to take a look at it tomorrow.

**Comment by michaelaird** [comment]
@ivogabe Your changes look good. enabling declaration maps by default if declarations are enabled makes total sense. Thanks!

**Pull request merged**
