### PR TITLE
Enable output filter in intelliJ by full file name, adjust error message...

### PR DESCRIPTION
**Pull request by jzalucki**
... so intelliJ can show error in file after file watcher run.

### CODE REVIEW

**Comment by ivogabe** [comment]
I think it would be better to write a custom reporter for this. Can you that instead?

**Comment by jzalucki** [comment]
I was considering that at the beginning, but custom reporters get narrowed down context. Of course it can be fixed but additionally gulp task prints error even without reporter using message property:

_this.emit('error', new gutil.PluginError(PLUGIN_NAME, err.message));

and nobody wants double reporting so i use nullReporter. This is why I've decided to adjust original error message. I think that this change is small enough to consider it as acceptable.

**Comment by ivogabe** [comment]
You should see the error only once, even when you are using a reporter. Can you change you're gulp file somehow so you can use a reporter? Maybe filter typescript errors from the other place where errors are logged.

I think the right place for this feature is a reporter. The current approach will probably break the tests too, have you tried running `gulp test`?

**Comment by jzalucki** [comment]
Couldn't run tests ;] Looks like something is broken there. Checked on your master too, please confirm.

I've reverted my change and added new reporter. After double check it even occurs that all required information are passed to reporters. Currently I am using new reporter and silent error for default error reporting in intelliJ and everything works fine.

**Comment by ivogabe** [comment]
A few small things:
- You should check whether the error belongs to a file, since there can be global errors. See fullReporter how you should implement that
- Use single quotes instead of double
- Can you add it to readme? Also describe there that it can be used with IntelliJ.
- I'd prefer another name, I don't know which. Maybe something like `longReporter`, since it's a little longer then default, but not as big as fullReporter. The reference to IntelliJ can be in the listed in the readme.
- Can you add yourself to the contributors field in the package.json file?

**Comment by jzalucki** [comment]
Sorry for the delay but I was on holidays. All your remarks has been fixed. I didn't run tests because they are broken, please check them out and run before applying on master.

**Pull request merged**
