### PR TITLE
Update to @types

### PR DESCRIPTION
**Pull request by ivogabe**
Contains most of the changes in the [types branch](https://github.com/ivogabe/gulp-typescript/compare/types...demurgos:types) of @demurgos. Differences:

- @demurgos' branch contained both typings and `@types`, which caused conflicts. I removed typings, since that was not needed any more.
- `@types` are not used in the tests any more. TypeScript would automatically pick up these files, which broke several tests in @demurgos' branch.

### CODE REVIEW

**Comment by demurgos** [comment]
Hi,
I was able to install and successfully run all the tests from your branch without any error.

Unfortunately, looks like it created conflicts with my dependant project (your definitions for Node were leaking and caused a conflict with my own). I'm taking a look at it, I'll try to set up a minimal repo demonstrating my problem.

**Comment by ivogabe** [comment]
It might be necessary to mark `@types/node` as a `devDependency`. Then consumers should install the types for node themselves, but they probably already need to do that. The definition will then never conflict with any other installation.

**Comment by demurgos** [comment]
Here is [a demo project](https://github.com/demurgos/gulp-ts-types) using `gulp-typescript` to generate other gulp tasks.

Before running the following commands, I checked-out your branch `types`, ran `npm install`, `npm test` (no error) and `npm link` so I'll be able to test it with my own project.

```shell
$ git clone https://github.com/demurgos/gulp-ts-types.git
$ cd gulp-ts-types
$ npm install && typings install
$ tsc
node_modules/gulp-typescript/release/main.d.ts(1,1): error TS6053: File '/home/demurgos/projects/test/gulp-ts-types/node_modules/gulp-typescript/typings/tsd.d.ts' not found.
```
(this is the error we're trying to solve)

Now, I link it with the branch `types` of `gulp-typescript`:
```shell
$ npm link gulp-typescript
/home/demurgos/projects/test/gulp-ts-types/node_modules/gulp-typescript -> /usr/lib/node_modules/gulp-typescript -> /home/demurgos/projects/others/gulp-typescript
$ tsc
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(102,6): error TS2300: Duplicate identifier 'BufferEncoding'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(547,9): error TS2502: 'BuffType' is referenced directly or indirectly in its own type annotation.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(548,9): error TS2502: 'SlowBuffType' is referenced directly or indirectly in its own type annotation.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(549,26): error TS2300: Duplicate identifier 'Buffer'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(549,50): error TS2300: Duplicate identifier 'SlowBuffer'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(570,18): error TS2300: Duplicate identifier 'EventEmitter'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(611,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'Server' and 'EventEmitter'.
  Named property 'addListener' of types 'Server' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(611,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'Server' and 'EventEmitter'.
  Named property 'emit' of types 'Server' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(611,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'Server' and 'EventEmitter'.
  Named property 'on' of types 'Server' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(611,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'Server' and 'EventEmitter'.
  Named property 'once' of types 'Server' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(611,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'Server' and 'EventEmitter'.
  Named property 'prependListener' of types 'Server' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(611,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'Server' and 'EventEmitter'.
  Named property 'prependOnceListener' of types 'Server' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(611,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'Server' and 'EventEmitter'.
  Named property 'removeListener' of types 'Server' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(623,22): error TS2320: Interface 'ServerResponse' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'addListener' of types 'Writable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(623,22): error TS2320: Interface 'ServerResponse' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'emit' of types 'Writable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(623,22): error TS2320: Interface 'ServerResponse' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'on' of types 'Writable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(623,22): error TS2320: Interface 'ServerResponse' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'once' of types 'Writable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(623,22): error TS2320: Interface 'ServerResponse' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'prependListener' of types 'Writable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(623,22): error TS2320: Interface 'ServerResponse' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'prependOnceListener' of types 'Writable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(623,22): error TS2320: Interface 'ServerResponse' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'removeListener' of types 'Writable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(653,22): error TS2320: Interface 'ClientRequest' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'addListener' of types 'Writable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(653,22): error TS2320: Interface 'ClientRequest' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'emit' of types 'Writable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(653,22): error TS2320: Interface 'ClientRequest' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'on' of types 'Writable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(653,22): error TS2320: Interface 'ClientRequest' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'once' of types 'Writable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(653,22): error TS2320: Interface 'ClientRequest' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'prependListener' of types 'Writable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(653,22): error TS2320: Interface 'ClientRequest' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'prependOnceListener' of types 'Writable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(653,22): error TS2320: Interface 'ClientRequest' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'removeListener' of types 'Writable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(679,22): error TS2320: Interface 'IncomingMessage' cannot simultaneously extend types 'Readable' and 'EventEmitter'.
  Named property 'addListener' of types 'Readable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(679,22): error TS2320: Interface 'IncomingMessage' cannot simultaneously extend types 'Readable' and 'EventEmitter'.
  Named property 'emit' of types 'Readable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(679,22): error TS2320: Interface 'IncomingMessage' cannot simultaneously extend types 'Readable' and 'EventEmitter'.
  Named property 'on' of types 'Readable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(679,22): error TS2320: Interface 'IncomingMessage' cannot simultaneously extend types 'Readable' and 'EventEmitter'.
  Named property 'once' of types 'Readable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(679,22): error TS2320: Interface 'IncomingMessage' cannot simultaneously extend types 'Readable' and 'EventEmitter'.
  Named property 'prependListener' of types 'Readable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(679,22): error TS2320: Interface 'IncomingMessage' cannot simultaneously extend types 'Readable' and 'EventEmitter'.
  Named property 'prependOnceListener' of types 'Readable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(679,22): error TS2320: Interface 'IncomingMessage' cannot simultaneously extend types 'Readable' and 'EventEmitter'.
  Named property 'removeListener' of types 'Readable' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(733,18): error TS2300: Duplicate identifier 'Agent'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(791,18): error TS2300: Duplicate identifier 'Worker'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(1342,22): error TS2320: Interface 'REPLServer' cannot simultaneously extend types 'Interface' and 'ReadLine'.
  Named property 'pause' of types 'Interface' and 'ReadLine' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(1342,22): error TS2320: Interface 'REPLServer' cannot simultaneously extend types 'Interface' and 'ReadLine'.
  Named property 'resume' of types 'Interface' and 'ReadLine' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(1377,17): error TS2300: Duplicate identifier 'CompleterResult'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(1414,18): error TS2300: Duplicate identifier 'Script'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(3004,22): error TS2420: Class 'Readable' incorrectly implements interface 'ReadableStream'.
  Types of property 'pause' are incompatible.
    Type '() => Readable' is not assignable to type '{ (): ReadableStream; (): void; }'.
      Type 'Readable' is not assignable to type 'ReadableStream'.
        Property 'isPaused' is missing in type 'Readable'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(3170,22): error TS2420: Class 'Duplex' incorrectly implements interface 'ReadWriteStream'.
  Types of property 'pause' are incompatible.
    Type '() => Duplex' is not assignable to type '() => ReadWriteStream'.
      Type 'Duplex' is not assignable to type 'ReadWriteStream'.
        Property 'isPaused' is missing in type 'Duplex'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(3191,22): error TS2420: Class 'Transform' incorrectly implements interface 'ReadWriteStream'.
  Types of property 'pause' are incompatible.
    Type '() => Transform' is not assignable to type '() => ReadWriteStream'.
      Type 'Transform' is not assignable to type 'ReadWriteStream'.
        Property 'isPaused' is missing in type 'Transform'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(3216,5): error TS2309: An export assignment cannot be used in a module with other exported elements.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(3299,5): error TS2300: Duplicate identifier 'export='.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(3321,18): error TS2300: Duplicate identifier 'Domain'.
typings/globals/node/index.d.ts(176,3): error TS2403: Subsequent variable declarations must have the same type.  Variable 'cache' must be of type 'any', but here has type '{ [filename: string]: NodeModule; }'.
typings/globals/node/index.d.ts(177,3): error TS2403: Subsequent variable declarations must have the same type.  Variable 'extensions' must be of type 'any', but here has type 'NodeExtensions'.
typings/globals/node/index.d.ts(202,3): error TS2403: Subsequent variable declarations must have the same type.  Variable 'parent' must be of type 'any', but here has type 'NodeModule'.
typings/globals/node/index.d.ts(205,3): error TS2403: Subsequent variable declarations must have the same type.  Variable 'children' must be of type 'any[]', but here has type 'NodeModule[]'.
typings/globals/node/index.d.ts(238,3): error TS2403: Subsequent variable declarations must have the same type.  Variable 'Console' must be of type '{ new (stdout: WritableStream, stderr?: WritableStream): Console; prototype: Console; }', but here has type 'new (stdout: WritableStream) => Console'.
typings/globals/node/index.d.ts(244,6): error TS2300: Duplicate identifier 'BufferEncoding'.
typings/globals/node/index.d.ts(252,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'Buffer' must be of type '{ new (str: string, encoding?: string): Buffer; new (size: number): Buffer; new (array: Uint8Arra...', but here has type '{ new (str: string, encoding?: string): Buffer; new (size: number): Buffer; new (array: Uint8Arra...'.
typings/globals/node/index.d.ts(386,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'errno' must be of type 'string', but here has type 'number'.
typings/globals/node/index.d.ts(469,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'env' must be of type 'any', but here has type '{ [key: string]: string; PATH: string; }'.
typings/globals/node/index.d.ts(474,5): error TS2687: All declarations of 'exitCode' must have identical modifiers.
typings/globals/node/index.d.ts(482,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'versions' must be of type 'ProcessVersions', but here has type '{ http_parser: string; node: string; v8: string; ares: string; uv: string; zlib: string; openssl:...'.
typings/globals/node/index.d.ts(673,24): error TS2300: Duplicate identifier 'Buffer'.
typings/globals/node/index.d.ts(673,48): error TS2300: Duplicate identifier 'SlowBuffer'.
typings/globals/node/index.d.ts(694,16): error TS2300: Duplicate identifier 'EventEmitter'.
typings/globals/node/index.d.ts(694,16): error TS2420: Class 'EventEmitter' incorrectly implements interface 'NodeJS.EventEmitter'.
  Property 'prependListener' is missing in type 'EventEmitter'.
typings/globals/node/index.d.ts(730,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'port' must be of type 'number', but here has type 'string | number'.
typings/globals/node/index.d.ts(735,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type '{ [key: string]: any; }', but here has type 'OutgoingHeaders'.
typings/globals/node/index.d.ts(804,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type 'any', but here has type 'IncomingHeaders'.
typings/globals/node/index.d.ts(806,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'trailers' must be of type 'any', but here has type 'IncomingHeaders'.
typings/globals/node/index.d.ts(807,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'rawTrailers' must be of type 'any', but here has type 'string[]'.
typings/globals/node/index.d.ts(848,16): error TS2300: Duplicate identifier 'Agent'.
typings/globals/node/index.d.ts(890,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'addressType' must be of type 'number | "udp4" | "udp6"', but here has type 'string'.
typings/globals/node/index.d.ts(893,16): error TS2300: Duplicate identifier 'Worker'.
typings/globals/node/index.d.ts(1066,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'SNICallback' must be of type '(servername: string, cb: (err: Error, ctx: SecureContext) => any) => any', but here has type '(servername: string) => any'.
typings/globals/node/index.d.ts(1070,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'pfx' must be of type 'any', but here has type 'string | Buffer'.
typings/globals/node/index.d.ts(1071,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'key' must be of type 'any', but here has type 'string | Buffer'.
typings/globals/node/index.d.ts(1073,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'cert' must be of type 'any', but here has type 'string | Buffer'.
typings/globals/node/index.d.ts(1074,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'ca' must be of type 'any', but here has type 'string | Buffer | (string | Buffer)[]'.
typings/globals/node/index.d.ts(1175,20): error TS2300: Duplicate identifier 'CompleterResult'.
typings/globals/node/index.d.ts(1222,16): error TS2300: Duplicate identifier 'Script'.
typings/globals/node/index.d.ts(2011,14): error TS2403: Subsequent variable declarations must have the same type.  Variable 'StringDecoder' must be of type 'new (encoding?: string) => NodeStringDecoder', but here has type 'new (encoding: string) => NodeStringDecoder'.
typings/globals/node/index.d.ts(2026,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'port' must be of type 'number', but here has type 'string | number'.
typings/globals/node/index.d.ts(2027,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'pfx' must be of type 'string | Buffer[]', but here has type 'string | Buffer'.
typings/globals/node/index.d.ts(2028,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'key' must be of type 'string | any[] | string[] | Buffer', but here has type 'string | Buffer'.
typings/globals/node/index.d.ts(2030,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'cert' must be of type 'string | string[] | Buffer | Buffer[]', but here has type 'string | Buffer'.
typings/globals/node/index.d.ts(2031,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'ca' must be of type 'string | string[] | Buffer | Buffer[]', but here has type 'string | Buffer | (string | Buffer)[]'.
typings/globals/node/index.d.ts(2034,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'honorCipherOrder' must be of type 'boolean', but here has type 'any'.
typings/globals/node/index.d.ts(2037,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'NPNProtocols' must be of type 'string[] | Buffer', but here has type '(string | Buffer)[]'.
typings/globals/node/index.d.ts(2038,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'SNICallback' must be of type '(servername: string, cb: (err: Error, ctx: SecureContext) => any) => any', but here has type '(servername: string) => any'.
typings/globals/node/index.d.ts(2043,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'port' must be of type 'number', but here has type 'string | number'.
typings/globals/node/index.d.ts(2046,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'key' must be of type 'string | string[] | Buffer | Buffer[]', but here has type 'string | Buffer'.
typings/globals/node/index.d.ts(2048,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'cert' must be of type 'string | string[] | Buffer | Buffer[]', but here has type 'string | Buffer'.
typings/globals/node/index.d.ts(2091,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'key' must be of type 'string | Buffer', but here has type 'string | string[] | Buffer | { pem: string; passphrase: string; }[]'.
typings/globals/node/index.d.ts(2196,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'padding' must be of type 'number', but here has type 'any'.
typings/globals/node/index.d.ts(2201,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'padding' must be of type 'number', but here has type 'any'.
typings/globals/node/index.d.ts(2220,16): error TS2420: Class 'Readable' incorrectly implements interface 'ReadableStream'.
  Types of property 'pause' are incompatible.
    Type '() => void' is not assignable to type '{ (): ReadableStream; (): void; }'.
      Type 'void' is not assignable to type 'ReadableStream'.
typings/globals/node/index.d.ts(2258,16): error TS2420: Class 'Duplex' incorrectly implements interface 'ReadWriteStream'.
  Types of property 'pause' are incompatible.
    Type '() => void' is not assignable to type '() => ReadWriteStream'.
      Type 'void' is not assignable to type 'ReadWriteStream'.
typings/globals/node/index.d.ts(2272,16): error TS2420: Class 'Transform' incorrectly implements interface 'ReadWriteStream'.
  Types of property 'pause' are incompatible.
    Type '() => void' is not assignable to type '() => ReadWriteStream'.
      Type 'void' is not assignable to type 'ReadWriteStream'.
typings/globals/node/index.d.ts(2366,3): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(2388,16): error TS2300: Duplicate identifier 'Domain'.
```

As you can see, your internal definitions are leaking and conflicting with my owns. This is pretty bad: this means that it might collide not only with my local definitions but also with the definitions of my other dependencies! I am currently using `typings` to get my dependencies, but for completeness I also checked with `tsd` (see the branch `tsd`):

```shell
$ tsc
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(102,6): error TS2300: Duplicate identifier 'BufferEncoding'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(263,18): error TS2300: Duplicate identifier 'EventEmitter'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(547,9): error TS2502: 'BuffType' is referenced directly or indirectly in its own type annotation.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(548,9): error TS2502: 'SlowBuffType' is referenced directly or indirectly in its own type annotation.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(549,26): error TS2300: Duplicate identifier 'Buffer'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(549,50): error TS2300: Duplicate identifier 'SlowBuffer'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(570,18): error TS2300: Duplicate identifier 'EventEmitter'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(733,18): error TS2300: Duplicate identifier 'Agent'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(791,18): error TS2300: Duplicate identifier 'Worker'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(1377,17): error TS2300: Duplicate identifier 'CompleterResult'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(1414,18): error TS2300: Duplicate identifier 'Script'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(1796,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'Socket' and 'EventEmitter'.
  Named property 'removeListener' of types 'Socket' and 'EventEmitter' are not identical.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(2320,18): error TS2451: Cannot redeclare block-scoped variable 'constants'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(2550,18): error TS2300: Duplicate identifier 'TLSSocket'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(2861,10): error TS2300: Duplicate identifier 'Utf8AsciiLatin1Encoding'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(2862,10): error TS2300: Duplicate identifier 'HexBase64Latin1Encoding'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(2863,10): error TS2300: Duplicate identifier 'Utf8AsciiBinaryEncoding'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(2864,10): error TS2300: Duplicate identifier 'HexBase64BinaryEncoding'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(2865,10): error TS2300: Duplicate identifier 'ECDHKeyFormat'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(3216,5): error TS2300: Duplicate identifier 'export='.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(3299,5): error TS2300: Duplicate identifier 'export='.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(3321,18): error TS2300: Duplicate identifier 'Domain'.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(3613,5): error TS2300: Duplicate identifier 'export='.
../../others/gulp-typescript/node_modules/@types/node/index.d.ts(3639,5): error TS2300: Duplicate identifier 'export='.
typings/node/node.d.ts(87,6): error TS2300: Duplicate identifier 'BufferEncoding'.
typings/node/node.d.ts(243,18): error TS2300: Duplicate identifier 'EventEmitter'.
typings/node/node.d.ts(530,26): error TS2300: Duplicate identifier 'Buffer'.
typings/node/node.d.ts(530,50): error TS2300: Duplicate identifier 'SlowBuffer'.
typings/node/node.d.ts(551,18): error TS2300: Duplicate identifier 'EventEmitter'.
typings/node/node.d.ts(714,18): error TS2300: Duplicate identifier 'Agent'.
typings/node/node.d.ts(772,18): error TS2300: Duplicate identifier 'Worker'.
typings/node/node.d.ts(1358,22): error TS2300: Duplicate identifier 'CompleterResult'.
typings/node/node.d.ts(1398,18): error TS2300: Duplicate identifier 'Script'.
typings/node/node.d.ts(2291,22): error TS2451: Cannot redeclare block-scoped variable 'constants'.
typings/node/node.d.ts(2646,18): error TS2300: Duplicate identifier 'TLSSocket'.
typings/node/node.d.ts(3020,10): error TS2300: Duplicate identifier 'Utf8AsciiLatin1Encoding'.
typings/node/node.d.ts(3021,10): error TS2300: Duplicate identifier 'HexBase64Latin1Encoding'.
typings/node/node.d.ts(3022,10): error TS2300: Duplicate identifier 'Utf8AsciiBinaryEncoding'.
typings/node/node.d.ts(3023,10): error TS2300: Duplicate identifier 'HexBase64BinaryEncoding'.
typings/node/node.d.ts(3024,10): error TS2300: Duplicate identifier 'ECDHKeyFormat'.
typings/node/node.d.ts(3375,5): error TS2300: Duplicate identifier 'export='.
typings/node/node.d.ts(3458,5): error TS2300: Duplicate identifier 'export='.
typings/node/node.d.ts(3480,18): error TS2300: Duplicate identifier 'Domain'.
typings/node/node.d.ts(3772,5): error TS2300: Duplicate identifier 'export='.
typings/node/node.d.ts(3798,5): error TS2300: Duplicate identifier 'export='.
```

I also tried with `@types` (see the branch `types`) and it worked. I'm still confused about it: we both used the exact same file in `@types`: what would happen when Node 7.x is released and I update my definitions before you do. Will my definitions conflict with yours internal ones ?


Finally, I know that `@types` is out now, but I'm not sure that a dependency should dictate the definition manager to use (or at least not right now when `@types` is only a few weeks old). As I told you in the related issue, you can use whatever definition manager you want, but for the moment I'd prefer to keep `typings` for my top project for various reasons so it would be fine if using your library did not break it. :s

I may also have made a mistake in my configuration so it may be possible to make it work with `tsd` or `typings` while your packages uses `@types`, in this case, could you please check what should be changed ?

**Comment by demurgos** [comment]
> It might be necessary to mark `@types/node` as a `devDependency`. Then consumers should install the types for node themselves, but they probably already need to do that. The definition will then never conflict with any other installation.

This may solve the issue: it seems that this is what Angular is using.

**Comment by ivogabe** [comment]
I'm pretty sure that making Node a devDependency will solve all issues. The other type definitions will never conflict with any other version of the package, since these can be installed multiple times without problems. However, that's not the case for Node since these types are declared like `declare module "fs" { .. }` (I guess they are called 'global' definitions), and they will pollute the global namespace. So a consumer of gulp-typescript would then only need to install the types for Node manually, all other types will be loaded automatically.

**Comment by demurgos** [comment]
I think that you are right. I asked how `@types/node` should be install (`dependency` or `devDependency`) on the `types-publisher` repo (https://github.com/Microsoft/types-publisher/issues/173), we should get an answer soon.

**Comment by demurgos** [comment]
I was looking for a source confirming that the way to go is to use `devDependencies`, I think that I got it: [Typescript](https://github.com/Microsoft/TypeScript/blob/master/package.json) itself is adding it as a `devDependency`.

**Comment by demurgos** [comment]
Hi!
[I got an answer](https://github.com/Microsoft/types-publisher/issues/81#issuecomment-255659806):

> My thought is `dependencies` since you're written as a library with dependents. For any users using Typings with TypeScript 1.8 and below, they shouldn't be affected, but as you noted, 2.0+ users may run into problems (at which point the solution is trivial - just remove `node` from their `typings.json` - but still annoying).

So keep it in `dependencies`, and I'll update my build to use `@type/node` and `typings` for the rest.

I think that this means that you can merge the current branch.

**Comment by demurgos** [comment]
Once you have accepted this PR, could you publish your package to npm ?

**Comment by ivogabe** [comment]
Yes, will create a new release then. Though I'm still afraid that this would break a lot of users, so replied to Microsoft/types-publisher#81, asking about possible conflicts.

**Pull request merged**
