### PR TITLE
Ignore tsbuildinfo in emit

### LINKED ISSUE #626: Change in Typescript 3.6 API causes TypeError when using incremental
**Expected behavior:**
All Typescript files in project successfully compiled

**Actual behavior:**
Crashes with the following error:
```
[16:15:44] TypeError: Cannot read property 'length' of undefined
    at Object.emit [as writeFile] (/home/dara/git/web-services/node_modules/gulp-typescript/release/compiler.js:82:33)
    at Object.writeFile (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:12098:14)
    at emitBuildInfo (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:86238:16)
    at emitSourceFileOrBundle (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:86205:13)
    at forEachEmittedFile (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:85999:28)
    at Object.emitFiles (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:86184:9)
    at emitWorker (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:92134:33)
    at /home/dara/git/web-services/node_modules/typescript/lib/typescript.js:92095:66
    at runWithCancellationToken (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:92185:24)
    at Object.emit (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:92095:20)
```
**Your gulpfile:**
```js
function compile() {
  const tsProject = ts.createProject('tsconfig.json');
  return tsProject.src()
    .pipe(tsProject())
    .pipe(dest('dist'));
}

exports.compile = compile;
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "rootDir": ".",
    "outDir": "dist",
    "module": "commonjs",
    "strict": true,
    "sourceMap": true,
    "incremental": true,
    "lib": ["esnext"],
    "target": "esnext",
    "noImplicitAny": false,
    "esModuleInterop": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": []
}
```
**My analysis**
With Typescript 3.6, the [write file callback](https://github.com/ivogabe/gulp-typescript/blob/master/lib/compiler.ts#L132L142) gets called not just with the js files emitted by the Typescript compiler, but also with the `tsconfig.tsbuildinfo` file, which has no source files so the `sourceFiles` parameter is `undefined`.

This only happens when `incremental` is set to true and doesn't happen in Typescript 3.5 because the `tsconfig.tsbuildinfo` was not passed to the callback.

This is likely an intentional change in Typescript, as the `tsc` command emits a `tsconfig.tsbuildinfo` file, but until now, it was not given to the write callback.

### PR DESCRIPTION
**Pull request by ivogabe**
Fixes #626. 

Note that this does not make the compiler incremental, it just prevents a crash. The new variant of incremental compilation is future work.

### CODE REVIEW

**Comment by DataTables** [comment]
Any idea when this will be merged in? I was about to send a similar PR to ignore tsbuildinfo since it means that composite projects can't be used at all with TS3.6+ with gulp-typescript.

**Comment by simllll** [comment]
Is this already released? I  still experiecing exactly this issue #626
[19:15:32] TypeError: Cannot read property 'length' of undefined
    at Object.writeFile (/home/simon/Dev/hokify/hokify-frontend/node_modules/gulp-typescript/release/compiler.js:81:33)

when composite is true

**Comment by ivogabe** [comment]
It's released in 6.0.0-alpha.1. Are you using that version? If so, you may run into a different similar issue, could you then create a minimal reproduction and open a new issue?

**Comment by simllll** [comment]
Just saw the alpha, thanks. I can confirm this works now for me :-) thanks for your effort!

**Pull request merged**
