### PR TITLE
Add support for TS3.0 projectReferences

### PR DESCRIPTION
**Pull request by rbuckton**
Adds support for building projects using TS 3.0 project references.

### CODE REVIEW

**Comment by rbuckton** [comment]
@ivogabe Can you take a look? Unfortunately, TypeScript itself can no longer use gulp-typescript in 'master' until minimal project reference support is added.

**Comment by rbuckton** [comment]
Not certain what's causing the test failure, as it is passing on my machine.

**Comment by ivogabe** [comment]
Thanks for the PR, will take a look at it this weekend. I’ll also look at the test failure.

**Comment by ivogabe** [comment]
When I run the tests, I get the following diff with your baselines: 53823ab56aeba6cec3df23978772399bafa25bc3. The CI probably has the same errors, I'm not sure why it doesn't show that in the output though. Is that baseline correct? Or is this not intended?

Other than that, the changes are good and can be merged.

**Comment by ivogabe** [comment]
(Could the difference in output for the test be caused by Windows versus Linux/Mac?)

**Comment by rbuckton** [comment]
@ivogabe I found the issue and updated the PR.

**Comment by ivogabe** [comment]
Thanks for the PR, released as 5.0.0-alpha.2

**Pull request merged**
